module.exports = {
    'Registration Statements': {
        "color": "success",
        "filingArray": [
            "S-1",
            "S-1/A",
            "S-1MEF",
            "POS AM",
            "S-2",
            "S-2/A",
            "S-2MEF",
            "S-3",
            "S-3/A",
            "S-3MEF",
            "S-3D",
            "S-3D/A",
            "S-3DPOS",
            "S-4",
            "S-4/A",
            "S-4EF",
            "S-4EF/A",
            "S-4 POS",
            "S-4MEF",
            "S-6",
            "S-6/A",
            "S-8",
            "S-8/A",
            "S-8 POS",
            "S-11",
            "S-11/A",
            "S-11MEF",
            "S-20",
            "S-20/A",
            "SB-1",
            "SB-1/A",
            "SB-1MEF",
            "SB-2",
            "SB-2/A",
            "SB-2MEF",
            "POS AM",
            "POS AMI",
            "424A",
            "424B1",
            "424B2",
            "424B3",
            "424B4",
            "424B5",
            "425",
            "DEL AM",
            "497",
            "497J",
            "S-6",
            "S-6/A",
            "497K1",
            "487",
            "10-12B",
            "10-12B/A",
            "10-12G",
            "10-12G/A",
            "10SB12B",
            "10SB12B/A",
            "10SB12G",
            "10SB12G/A",
            "18-12B",
            "18-12B/A",
            "18-12G",
            "18-12G/A",
            "N-8B-2",
            "N-8B-2/A",
            "N-1",
            "N-1/A",
            "N-1A",
            "N-2",
            "N-2/A",
            "N-3",
            "N-3/A",
            "N-4",
            "N-4/A",
            "N-5",
            "N-5/A",
            "N-14",
            "N-14/A",
            "N-14/AE",
            "N-14/AE/A",
            "N-14 8C",
            "N-14 8C/A",
            "F-1",
            "F-1/A",
            "F-1MEF",
            "F-2",
            "F-2/A",
            "F-2D",
            "F-2DPOS",
            "F-2MEF",
            "F-3MEF",
            "F-4MEF",
            "F-9MEF",
            "F-10MEF",
            "F-3",
            "F-3/A",
            "F-3D",
            "F-3DPOS",
            "F-4",
            "F-4/A",
            "F-6",
            "F-6/A",
            "F-6 POS",
            "F-6EF",
            "F-6EF/A",
            "20FR12B",
            "20FR12B/A",
            "20FR12G",
            "20FR12G/A",
            "24F-1",
            "24F-2EL",
            "24F-2EL/A",
            "24F-2NT",
            "24F-2NT/A",
            "POS462B",
            "POS462C",
            "8-A12B",
            "8-A12B/A",
            "8-A12G",
            "8-A12G/A",
            "8-B12B",
            "8-B12B/A",
            "8-B12G",
            "8-B12G/A",
            "8A12BEF",
            "8A12BT",
            "8A12BT/A",
            "485A24E",
            "485A24F",
            "485APOS",
            "485B24E",
            "485B24F",
            "485BPOS"
        ],
        "descriptionArray": [
            "This filing is a pre-effective registration statement submitted when a company decides to go public. Commonly referred to as an 'IPO' (Initial Public Offering) filing.",
            "This filing is a pre-effective amendment to an S-1 IPO filing.",
            "Registration of up to an additional 20% of securities for any offering registered on an S-1.",
            "This filing is a post-effective amendment to an S-Type filing.",
            "This filing is an optional registration form that may be used by companies which have reported under the '34 Act for a minimum of three years and have timely filed all required reports during the 12 calendar months and any portion of the month immediately preceding the filing of the registration statement.",
            "This filing is a pre-effective amendment to an S-2 filing.",
            "Registration of up to an additional 20% of securities for any offering registered on an S-2.",
            "This filing is the most simplified registration form and it may only be used by companies which have reported under the '34 Act for a minimum of twelve months and meet the timely filing requirements set forth under Form S-2. The filing company must also meet the stringent qualitative tests prescribed by the form.",
            "This filing is a pre-effective amendment to an S-3 filing.",
            "Registration of up to an additional 20% of securities for any offering registered on a S-3.",
            "Registration statement of securities pursuant to dividend or interest reinvestment plans which become effective automatically upon filing.",
            "Amendment to a previously filed S-3D.",
            "This filing is a post-effective amendment to an S-3D filing.",
            "This filing is for the registration of securities issued in business combination transactions.",
            "This filing is a pre-effective amendment to an S-4 filing.",
            "Filed when securities are issued in connection with the formation of a bank, savings and loan, or holding company.",
            "This filing is a pre-effective amendment to an S-4EF filing.",
            "This filing is a post-effective amendment to an S-4EF filing.",
            "Registration pursuant to Securities Act Rule 462(b) of up to an additional 20% of securities for an offering that was registered on a Form S-3.",
            "Initial registration statement for unit investment trusts.",
            "This filing is a pre-effective amendment to an S-6 filing.",
            "This filing is required when securities are to be offered to employees pursuant to employee benefit plans.",
            "Amendment to a previously filed S-8.",
            "This filing is a post-effective amendment to an S-8 filing.",
            "Filing for the registration of securities of certain real estate companies.",
            "This filing is a pre-effective amendment to an S-11 filing.",
            "Registration of up to an additional 20% of securities for any offering registered on a S-11.",
            "Initial registration statement for standardized options.",
            "Amendment to a previously filed S-20.",
            "An optional filing for small business issuers for the registration of securities to be sold to the public.",
            "This filing is a pre-effective amendment to an SB-1 filing.",
            "Registration of up to an additional 20% of securities for any offering registered on a SB-1.",
            "Also an optional filing for small business issuers for the registration of securities to be sold to the public.",
            "This filing is a pre-effective amendment to an SB-2 filing.",
            "Registration of up to an additional 20% of securities for any offering registered on a SB-2.",
            "Post-effective amendments.",
            "Post-effective amendments.",
            "Contains substantive changes from or additions to a prospectus previously filed with the SEC as part of the registration statement.",
            "A form of prospectus that discloses information previously omitted from the prospectus filed as part of a registration statement.",
            "A form of prospectus filed in connection with a primary offering of securities on a delayed basis which includes the public offering price, description of securities and specific method of distribution.",
            "A form of prospectus that reflects facts or events that constitute a substantive change from or addition to the information set forth in the last form of prospectus filed with the SEC.",
            "A form of prospectus that discloses information, facts or events covered in both form 424B1 and form 424B3.",
            "A form of prospectus that discloses information, facts or events covered in both form 424B2 and form 424B3.",
            "Filing of certain prospectuses and communications in connection with business combination transactions.",
            "Delaying amendment.",
            "Definitive materials filed by investment companies.",
            "Certification of no change in definitive materials.",
            "Registration statement for unit investment trusts.",
            "Pre-effective amendment to a S-6.",
            "Profiles for certain open-end management investment companies.",
            "Pre-effective pricing amendment.",
            "A general registration filing of securities pursuant to section 12(b) of the Securities Exchange Act.",
            "Amendment to a previously filed 10-12B.",
            "A general registration filing of securities pursuant to section 12(g) of the Securities Exchange Act.",
            "Amendment to a previously filed 10-12G.",
            "Filed for the registration of securities for small business issuers pursuant to section 12(b) of the Securities Exchange Act.",
            "Amendment to a previously filed 10SB12B.",
            "Filed for the registration of securities for small business issuers pursuant to section 12(g) of the Securities Exchange Act.",
            "Amendment to a previously filed 10SB12G.",
            "Registration of securities filed pursuant to section 12(b) of the Securities Exchange Act.",
            "Amendment to a previously filed 18-12B.",
            "Registration of securities filed pursuant to section 12(g) of the Securities Exchange Act.",
            "Amendment to a previously filed 18-12G.",
            "Registration statement for unit investment trusts.",
            "Amendments to a previously filed N-8B-2.",
            "Registration statement for open-end management investment companies.",
            "Amendments to a previously filed N-1.",
            "Registration statement for Mutual Funds.",
            "Registration statement for closed-end investment companies.",
            "This filing is a pre-effective amendment to an N-2 filing.",
            "Registration statement for separate accounts (management investment companies).",
            "This filing is a pre-effective amendment to an N-3 filing.",
            "Registration statement for separate accounts (unit investment trusts).",
            "This filing is a pre-effective amendment to an N-4 filing.",
            "Registration statement for small business investment companies.",
            "This filing is a pre-effective amendment to an N-5 filing.",
            "Registration statement for investment companies business combination.",
            "Pre-effective amendment to a previously filed N-14.",
            "Initial statement with automatic effectiveness.",
            "Pre-effective amendment.",
            "Registration statement for closed-end investment company.",
            "Pre-effective amendment.",
            "Registration statement for certain foreign private issuers.",
            "This filing is a pre-effective amendment to an F-1 filing.",
            "Registration of up to an additional 20% of securities for an offering filed on an F-1.",
            "Registration statement for certain foreign private issuers.",
            "Amendment to a previously filed F-2.",
            "Registration of securities pursuant to dividend or interest reinvestment plans (foreign).",
            "Post-effective amendments to a previously filed F-2D.",
            "Registration pursuant to Securities Act Rule 462(b) of up to an additional 20% of securities for an offering that was registered on a Form F-2.",
            "Registration pursuant to Securities Act Rule 462(b) of up to an additional 20% of securities for an offering that was registered on a Form F-3.",
            "Registration pursuant to Securities Act Rule 462(b) of up to an additional 20% of securities for an offering that was registered on a Form F-4.",
            "Registration pursuant to Securities Act Rule 462(b) of up to an additional 20% of securities for an offering that was registered on a Form F-9.",
            "Registration pursuant to Securities Act Rule 462(b) of up to an additional 20% of securities for an offering that was registered on a Form F-10.",
            "Registration statement for certain foreign private issuers offered pursuant to certain types of transactions.",
            "Amendment to a previously filed F-3.",
            "Registration statement for certain foreign private issuers offered pursuant to dividend or pursuant to dividend or interest reinvestment plans.",
            "Amendment to a previously filed F-3D.",
            "Registration statement for foreign private issuers issued in certain business transactions.",
            "Amendment to a previously filed F-4.",
            "Registration of depository shares evidenced by American Depository Receipts. Filing to become effective other than immediately upon filing.",
            "Amendment to a previously filed F-6.",
            "Post-effective amendment to a previously filed F-6.",
            "Registration of depositary shares evidenced by American Depository Receipts. Filing to become effective immediately upon filing.",
            "Amendment to a previously filed F-6EF.",
            "Registration of securities of foreign private issuers pursuant to section 12 (b) of the Securities Exchange Act.",
            "Amendment to a previously filed 20FR12B.",
            "Registration of securities of foreign private issuers pursuant to section 12 (g) of the Securities Exchange Act.",
            "Amendment to a previously filed 20FR12G.",
            "Registration of securities by certain investment companies pursuant to rule 24f-1. Notification of election.",
            "Registration of securities by certain investment companies pursuant to rule 24f-2. Declaration of election.",
            "Amendment to a previously filed 24F-2EL.",
            "Registration of securities by certain investment companies pursuant to rule 24f-2. Rule 24f-2 notice.",
            "Amendment to a previously filed 24F-2NT.",
            "Post effective amendment to proposed Securities Act Rule 462(b) registration statement.",
            "Post effective amendment to proposed Securities Act Rule 462(c) registration statement.",
            "Registration of certain classes of securities pursuant to section 12(b) of the Securities Exchange Act.",
            "Amendment to a previously filed 8-A12B.",
            "Registration of certain classes of securities pursuant to section 12(g) of the Securities Exchange Act.",
            "Amendment to a previously filed 8-A12G.",
            "Registration of securities of certain successor issuers pursuant to section 12(b) of the Securities Exchange Act.",
            "Amendment to a previously filed 8-B12B.",
            "Registration of securities of certain successor issuers pursuant to section 12(g) of the Securities Exchange Act.",
            "Amendment to a previously filed 8-B12G.",
            "Registration of listed debt securities pursuant to section 12(b) - filing to become effective automatically upon filing.",
            "Registration of listed debt securities pursuant to section 12(b) - filing to become effective simultaneously with the effective of a concurrent Securities Act registration statement.",
            "Amendment to a previously filed 8A12BT.",
            "Registration statement for separate accounts (management investment companies). Post-Effective amendment filed pursuant to Rule 485(b) with additional shares under 24e-2.",
            "Registration statement for separate accounts (management investment companies). Post-Effective amendment filed pursuant to Rule 485(b) with additional shares under 24f-2.",
            "Registration statement for separate accounts (management investment companies). Post-Effective amendment filed pursuant to Rule 485(a).",
            "Registration statement for separate accounts (management investment companies). Post-Effective amendment filed pursuant to Rule 485(a) with additional shares under 24e-2.",
            "Registration statement for separate accounts (management investment companies). Post-Effective amendment filed pursuant to Rule 485(b) with additional shares under 24f-2.",
            "Registration statement for separate accounts (management investment companies). Post-Effective amendment filed pursuant to Rule 485(b)."
        ]
    },
    "Registration Withdrawal and Termination Statements": {
        "color": "danger",
        "filingArray": [
            "RW",
            "AW",
            "15-12G",
            "15-12G/A",
            "15-15D",
            "15-15D/A",
            "15-12B",
            "15-12B/A",
            "24F-2TM"
        ],
        "descriptionArray": [
            "Request for a withdrawal of a previously filed registration statement.",
            "Amendment to a previously filed RW.",
            "Certification of termination of registration of a class of security under Section 12(g) or notice of suspension of duty to file reports pursuant to Section 13 and 15(d) of the Securities Exchange Act. Section 12 (g) initial filing.",
            "Amendment to a previously filed 15-12G.",
            "Certification of termination of registration of a class of security under Section 12(g) or notice of suspension of duty to file reports pursuant to Section 13 and 15(d) of the Securities Exchange Act. Section 13 and 15 (d) initial filing.",
            "Amendment to a previously filed 15-15D.",
            "Certification of termination of registration of a class of security under Section 12(g) or notice of suspension of duty to file reports pursuant to Section 13 and 15(d) of the Securities Exchange Act. Section 12 (b) initial filing.",
            "Amendment to a previously filed 15-12B.",
            "Registration of securities by certain investment companies pursuant to rule 24f-2. Termination of declaration of election."
        ]
    },
    "Proxies and Information Statements": {
        "color": "primary",
        "filingArray": [
            "PRE 14A",
            "PREC14A",
            "PREC14C",
            "PREN14A",
            "PREM14A",
            "PREM14C",
            "PRES14A",
            "PRES14C",
            "PRE 14C",
            "PRER14A",
            "PRER14C",
            "PRE13E3",
            "PRE13E3/A",
            "PRRN14A",
            "PX14A6G",
            "DEF 14A",
            "DEFM14A",
            "DEFM14C",
            "DEFS14A",
            "DEFS14C",
            "DEFC14A",
            "DEFC14C",
            "DEFA14A",
            "DEFN14A",
            "DFRN14A",
            "DFAN14A",
            "DEF13E3",
            "DEF13E3/A",
            "DEFA14C",
            "DEFR14C",
            "DEFR14A"
        ],
        "descriptionArray": [
            "A preliminary proxy statement providing official notification to designated classes of shareholders of matters to be brought to a vote at a shareholders meeting.",
            "Preliminary proxy statement containing contested solicitations.",
            "Preliminary information statement containing contested solicitations.",
            "Non-management preliminary proxy statements not involving contested solicitations.",
            "A preliminary proxy statement relating to a merger or acquisition.",
            "A preliminary information statement relating to a merger or acquisition.",
            "A preliminary proxy statement giving notice regarding a special meeting.",
            "A preliminary information statement relating to a special meeting.",
            "A preliminary proxy statement containing all other information.",
            "Proxy soliciting materials. Revised preliminary material.",
            "Information statements. Revised preliminary material.",
            "Initial statement - preliminary form.",
            "Amendment to a previously filed PRE13E3.",
            "Non-management revised preliminary proxy soliciting materials for both contested solicitations and other situations. Revised preliminary material.",
            "Notice of exempt solicitation. Definitive material.",
            "Provides official notification to designated classes of shareholders of matters to be brought to a vote at a shareholders meeting. This form is commonly refered to as a 'Proxy'.",
            "Provides official notification to designated classes of shareholders of matters relating to a merger or acquisition.",
            "A definitive information statement relating to a merger or an acquisition.",
            "A definitive proxy statement giving notice regarding a special meeting.",
            "A definitive information statement regarding a special meeting.",
            "Definitive proxy statement in connection with contested solicitations.",
            "Definitive information statement indicating contested solicitations.",
            "Additional proxy soliciting materials - definitive.",
            "Definitive proxy statement filed by non-management not in connection with contested solicitations.",
            "Revised definitive proxy statement filed by non-management.",
            "Additional proxy soliciting materials filed by non-management.",
            "Schedule filed as definitive materials.",
            "Amendment to a previously filed DEF 13E3.",
            "Additional information statement materials - definitive.",
            "Revised information statement materials - definitive.",
            "Revised proxy soliciting materials -definitive."
        ]
    },
    "Quarterly Reports": {
        "color": "teal",
        "filingArray": [
            "10-Q",
            "10-Q/A",
            "10QSB",
            "10QSB/A",
            "NT 10-Q",
            "NT 10-Q/A",
            "10-QT",
            "10-QT/A",
            "13F-E",
            "13F-E/A",
            "13F-HR",
            "13F-HR/A",
            "13F-NT",
            "13F-NT/A",
            "13F-HR",
            "13F-HR/A"
        ],
        "descriptionArray": [
            "A quarterly report which provides a continuing view of a company's financial position during the year. The filing is due 45 days after each of the first three fiscal quarters. No filing is due for the fourth quarter.",
            "Amendment to a previously filed 10-Q.",
            "A quarterly report which provides a continuing view of a company's financial position during the year. The 10QSB form is filed by small businesses.",
            "An amendment to a previously filed 10QSB.",
            "Notification that form type 10-Q will be submitted late.",
            "Amendment to a previously filed NT 10-Q.",
            "Quarterly transition reports filed pursuant to rule 13a-10 or 15d-10 of the Securities Exchange Act.",
            "Amendment to a previously filed 10-QT.",
            "Quarterly reports filed by institutional managers.",
            "Amendment to a previously filed 13F-E.",
            "13F Holdings Report Initial Filing 13F-HR.",
            "13F Holdings Report Initial Filing amendment13F-HR/A.",
            "13F Notice Report Initial Filing 13F-NT.",
            "13F Notice Report Initial Filing amendment13F-NT/A.",
            "13F Combination Report Initial Filing. 13F-HR.",
            "13F Combination Report Initial Filing amendment. 13F-HR/A."
        ]
    },
    "Annual Reports": {
        "color": "info",
        "filingArray": [
            "ARS",
            "10-K",
            "10-K/A",
            "10-K405",
            "10-K405/A",
            "NT 10-K",
            "NT 10-K/A",
            "10KSB",
            "10KSB/A",
            "10-C",
            "10-C/A",
            "10-KT",
            "10-KT/A",
            "10KSB40",
            "10KSB40/A",
            "10KT405",
            "10KT405/A",
            "11-KT",
            "11-KT/A",
            "18-K",
            "18-K/A",
            "11-K",
            "11-K/A",
            "NT 11-K",
            "NT 11-K/A",
            "NSAR-A",
            "NSAR-A/A",
            "NSAR-AT",
            "NSAR-AT/A",
            "NSAR-B",
            "NSAR-B/A",
            "NSAR-BT",
            "NSAR-BT/A",
            "NSAR-U",
            "NSAR-U/A",
            "NT-NSAR",
            "NT-NSAR/A",
            "N-30D",
            "N-30D/A",
            "20-F",
            "20-F/A",
            "ARS"
        ],
        "descriptionArray": [
            "An annual report to security holders. This is a voluntary filing on EDGAR.",
            "An annual report which provides a comprehensive overview of the company for the past year. The filing is due 90 days after the close of the company's fiscal year, and contains such information as company history, organization, nature of business, equity, holdings, earnings per share, subsidiaries, and other pertinent financial information.",
            "Amendment to a previously filed 10-K.",
            "An annual report which provides a comprehensive overview of the company for the past year. The Regulation S-K Item 405 box on the cover page is checked.",
            "This filing is an amendment to a previously filed 10-K405.",
            "Notification that form 10-K will be submitted late.",
            "Amendment to a previously filed NT 10-K.",
            "An annual report which provides a comprehensive overview of the company for the past year. The filing is due 90 days after the close of the company's fiscal year, and contains such information as company history, organization, nature of business, equity, holdings, earnings per share, subsidiaries, and other pertinent financial information. The 10KSB is filed by small businesses.",
            "Amendment to a previously filed 10KSB.",
            "This filing is required of an issuer of securities quoted on the NASDAQ Interdealer Quotation System, and contains information regarding a change in the number of shares outstanding or a change in the name of the issuer.",
            "Amendment to a previously filed 10-C.",
            "Annual transition reports filed pursuant to rule 13a-10 or 15d-10 of the Securities Exchange Act.",
            "Amendment to a previously filed 10-KT.",
            "An optional form for annual and transition reports of small business issuers under Section 13 or 15 (d) of the Securities Exchange Act where the Regulation S-B Item 405 box on the cover page (relating to section 16 (a) reports) is checked.",
            "Amendment to a previously filed 10KSB40.",
            "Annual transition report filed pursuant to Rule 13a-10 or15d-10 of the Securities Exchange Act.",
            "Amendment to a previously filed 10KT405.",
            "Annual report of employee stock purchase, savings and similar plans. Filed pursuant to rule 13a-10 or 15d-10 of the Securities Exchange Act.",
            "Amendment to a previously filed 11-KT.",
            "Annual report for foreign governments and political subdivisions.",
            "Amendment to a previously filed 18-K.",
            "An annual report of employee stock purchase, savings and similar plans.",
            "Amendment to a previously filed 11-K.",
            "Notification that form 11-K will be submitted late.",
            "Amendment to a previously filed NT 11-K.",
            "Semi-Annual report for management companies.",
            "Amendments to a previously filed NSAR-A.",
            "Transitional semi-annual report for registered investment companies (Management).",
            "Amendments to a previously filed NSAR-AT.",
            "Annual report for management companies.",
            "Amendments to a previously filed NSAR-B.",
            "Transitional annual report for management companies.",
            "Amendments to a previously filed NSAR-BT.",
            "Annual report for unit investment trusts.",
            "Amendments to a previously filed NSAR-U.",
            "Request for an extension of time for filing form NSAR-A, NSAR-B or NSAR-U.",
            "Amendments to a previously filed NT-NSAR.",
            "An annual and semi-annual report mailed to shareholders. Filed by registered investment companies.",
            "Amendments to a previously filed N-30D.",
            "Annual and transition report of foreign private issuers filed pursuant to sections 13 or 15 (d) of the Securities Exchange Act.",
            "Amendment to a previously filed 20-F.",
            "Annual report to Security Holders."
        ]
    },
    "Statements of Ownership": {
        "color": "light",
        "filingArray": [
            "SC 13D",
            "SC 13D/A",
            "SC 13G",
            "SC 13G/A",
            "SC 13E1",
            "SC 13E1/A",
            "SC 13E3",
            "SC 13E3/A",
            "SC 13E4",
            "SC 13E4/A",
            "SC 14D1",
            "SC 14D1/A",
            "SC 14D9",
            "SC 14D9/A",
            "SC 14F1",
            "SC 14F1/A",
            "SC TO-C",
            "SC TO-C/A",
            "SC TO-T",
            "SC TO-T/A",
            "SC TO-I",
            "SC TO-I/A"
        ],
        "descriptionArray": [
            "This filing is made by person(s) reporting beneficially owned shares of common stock in a public company.",
            "An amendment to a SC 13D filing.",
            "A statement of beneficial ownership of common stock by certain persons.",
            "An amendment to the SC 13G filing.",
            "Statement of issuer required by Rule 13e-1 of the Securities Exchange Act.",
            "Amendment to a previously filed SC 13E1.",
            "Going private transaction by certain issuers.",
            "Amendment to a previously filed SC 13E3.",
            "Issuer tender offer statement.",
            "Amendment to a previously filed SC 13E4.",
            "Tender offer statement.",
            "Amendment to a previously filed SC 14D1.",
            "Solicitation/recommendation statements.",
            "Amendment to a previously filed SC 14D9.",
            "Statement regarding change in majority of directors pursuant to Rule 14f-1.",
            "Amendment to a previously filed SC 14F1.",
            "Written public communication relating to an issuer or third party tender offer not by the subject company.",
            "Amendment to a previously filed SC TO-C.",
            "Tender offer schedule and amendment filed by a third party.",
            "Amendment to a previously filed SC TO-T",
            "Tender offer schedule and amendment filed by the issuer.",
            "Amendment to a previously filed SC TO-I."
        ]
    },
    "Insider Trading": {
        "color": "dark",
        "filingArray": [
            "3",
            "3/A",
            "4",
            "4/A",
            "5",
            "5/A",
            "144",
            "144/A"
        ],
        "descriptionArray": [
            "An initial filing of equity securities filed by every director, officer, or owner of more than ten percent of a class of equity securities. Contains information on the reporting person's relationship to the company and on purchases and sales of equity securities.",
            "An amendment to a 3 filing. This form is not required to be filed with the EDGAR system.",
            "Any changes to a previously filed form 3 are reported in this filing.",
            "Amendment to a previously filed 4.",
            "An annual statement of ownership of securities filed by every director, officer, or owner of more than ten percent of a class of equity securities. Contains information on the reporting person's relationship to the company and on purchases and sales of equity securities.",
            "Amendment to a previously filed 5.",
            "This form must be filed by 'insiders' prior to their intended sale of restricted stock (issued stock currently unregistered with the SEC). Filing this form results in each seller receiving an automatic exemption from SEC registration requirements for this one transaction. A Form 144 is NOT an EDGAR electronic filing; each 144 is filed by the seller in paper during the day at the SEC. EDGAR Online cumulates and adds all of the current day's 144 paper filings to our electronic database at the END of each business day. ",
            "Amendment to a previously filed 144."
        ]
    },
    "Filings pursuant to the Trust Identure Act": {
        "color": "danger",
        "filingArray": [
            "305B2",
            "305B2/A",
            "T-3",
            "T-3/A"
        ],
        "descriptionArray": [
            "Initial statement filed pursuant to the Trust Indenture Act.",
            "Amendment to a previously filed 305B2.",
            "Application for qualification of trust indentures. Filed pursuant to the Trust Indenture Act.",
            "Amendment to a previously filed T-3."
        ]
    },
    "Filings pursuant to the Public Utility Holding Company Act": {
        "color": "indigo",
        "filingArray": [
            "U-1",
            "U-1/A",
            "U-13-1",
            "U-13-1/A",
            "U-12-IB",
            "U-12-IB",
            "U-13E-1",
            "U-13E-1/A",
            "U-13-60",
            "U-13-60/A",
            "U-33-S",
            "U-3A-2",
            "U-3A-2/A",
            "U-3A3-1",
            "U-3A3-1/A",
            "U-57",
            "U-57/A",
            "U-6B-2",
            "U-7D",
            "U-7D/A",
            "U-R-1",
            "45B-3",
            "45B-3/A",
            "U5A",
            "U5B",
            "U5B/A",
            "U5S",
            "U-9C-3",
            "U-9C-3/A",
            "U-12-IA",
            "U-12-IA/A",
            "U5S/A",
            "35-APP",
            "35-APP/A",
            "35-CERT",
            "35-CERT/A"
        ],
        "descriptionArray": [
            "Application of declaration under the Public Utility Holding Company Act.",
            "Amendment to a previously filed U-1.",
            "Application for approval for mutual service company filed pursuant to Rule 88 of the Public Utility Holding Company Act.",
            "Amendment to a previously filed U-13-1.",
            "Annual statement pursuant to section 12(i) of the Public Utility Company Act or by a registered holding company or a subsidiary thereof.",
            "Amendment to a U-12-IB.",
            "Report by affiliate service companies or independent service companies.",
            "Amendment to a U-13E-1.",
            "Annual report for mutual and subsidiary service companies filed pursuant to Rule 94 of the Public Utility Holding Company Act.",
            "Amendment to a previously filed U-13-60.",
            "Annual report concerning Foreign Utility Companies pursuant to section 33(e) of the Public Utility Holding Company Act.",
            "Statement by holding company claiming exemption from provisions of the act pursuant to Rule 2.",
            "Amendment to a previously filed U-3A-2.",
            "Twelve-month statement by bank claiming exemption from provisions of the act pursuant to Rule 3 of the Public Utility Holding Company Act.",
            "Amendment to a previously filed U-3A3-1.",
            "Notification of Foreign Utility Company Status under section 33(a)(2) of the Public Utility Holding Company Act.",
            "Amendment to a previously filed U-57.",
            "Certificate of notification of security issue, renewal or guaranty filed pursuant to Rule 20(d) of the Public Utility Holding Company Act.",
            "Certificate concerning lease of a utility facility filed pursuant to Rule 7(d) of the Public Utility Holding Company Act.",
            "Amendment to a previously filed U-7D.",
            "Declaration as to solicitations filed pursuant to Rule 62 of the Public Utility Holding Company Act.",
            "Transitional initial statement concerning extensions of credit.",
            "Amendment to 45B-3.",
            "Notification of registration filed under section 5(a) of the Public Utility Holding Company Act.",
            "Registration statement filed under section 5 of the Public Utility Holding Company Act.",
            "Amendment to a previously filed U5B.",
            "Annual report for holding companies registered pursuant to section 5 of the Public Utility Holding Company Act.",
            "Quarterly report concerning energy and gas-related companies.",
            "Amendment to a U-9C-3.",
            "Statement pursuant to section 12(i) of the Act by person employed or retained by a registered holding company or subsidiary thereof.",
            "Amendment to a U-12-IA.",
            "Amendment to a previously filed U5S.",
            "Statement concerning proposed transaction for which no form of application is prescribed filed pursuant to Rule 20(e) of the Public Utility Holding Company Act.",
            "Amendment to a previously filed 35-APP.",
            "Certificate concerning terms and conditions filed pursuant to Rule 24 of the Public Utility Holding Company Act.",
            "Amendment to a previously filed 35-CERT."
        ]
    },
    "Miscellaneous Filings": {
        "color": "orange",
        "filingArray": [
            "8-K",
            "8-K/A",
            "N-14AE",
            "N-14AE/A",
            "N-30B-2",
            "2-E",
            "2-E/A",
            "SP 15D2",
            "SP 15D2/A",
            "NT 15D2",
            "NT 15D2/A",
            "6-K",
            "6-K/A",
            "8-K12G3",
            "8-K12G3/A",
            "8-K15D5",
            "8-K15D5/A"
        ],
        "descriptionArray": [
            "A report of unscheduled material events or corporate changes which could be of importance to the shareholders or to the SEC. Examples include acquisition, bankruptcy, resignation of directors, or a change in the fiscal year.",
            "Amendment to a previously filed 8-K.",
            "Initial statement with automatic effectiveness for investment companies business combination.",
            "Pre-effective amendment to a previously filed N-14AE.",
            "Periodic and interim reports mailed to shareholders. Filed by registered investment companies.",
            "Reports of sales of securities pursuant to Regulation E. Filed by investment companies.",
            "Amendment to a previously filed 2-E.",
            "Special financial report pursuant to Rule 15d-2 of the Securities Exchange Act.",
            "Amendments to a previously filed SP 15D2.",
            "Notification of late filing Special report pursuant to section 15d-2.",
            "Amendment to a previously filed NT 15D2.",
            "Report of foreign issuer pursuant to Rules 13a-16 and 15d-16 of the Securities Exchange Act.",
            "Amendment to a previously filed 6-K.",
            "Notification of securities of successor issuers deemed to be registered pursuant to section 12(g) of the Securities Exchange Act.",
            "Amendment to a previously filed 8-K12G3.",
            "Notification of assumption of duty to report by successor issuer.",
            "Amendment to a previously filed 8-K15D5."
        ]
    }
}