module.exports = {
    'Registration Statements': {
        "color": "success",
        "filingArray": [
            "S-1",
            "S-1/A",
            "S-1MEF",
            "POS AM",
            "S-2",
            "S-2/A",
            "S-2MEF",
            "S-3",
            "S-3/A",
            "S-3MEF",
            "S-3D",
            "S-3D/A",
            "S-3DPOS",
            "S-4",
            "S-4/A",
            "S-4EF",
            "S-4EF/A",
            "S-4 POS",
            "S-4MEF",
            "S-6",
            "S-6/A",
            "S-8",
            "S-8/A",
            "S-8 POS",
            "S-11",
            "S-11/A",
            "S-11MEF",
            "S-20",
            "S-20/A",
            "SB-1",
            "SB-1/A",
            "SB-1MEF",
            "SB-2",
            "SB-2/A",
            "SB-2MEF",
            "POS AM",
            "POS AMI",
            "424A",
            "424B1",
            "424B2",
            "424B3",
            "424B4",
            "424B5",
            "425",
            "DEL AM",
            "497",
            "497J",
            "S-6",
            "S-6/A",
            "497K1",
            "487",
            "10-12B",
            "10-12B/A",
            "10-12G",
            "10-12G/A",
            "10SB12B",
            "10SB12B/A",
            "10SB12G",
            "10SB12G/A",
            "18-12B",
            "18-12B/A",
            "18-12G",
            "18-12G/A",
            "N-8B-2",
            "N-8B-2/A",
            "N-1",
            "N-1/A",
            "N-1A",
            "N-2",
            "N-2/A",
            "N-3",
            "N-3/A",
            "N-4",
            "N-4/A",
            "N-5",
            "N-5/A",
            "N-14",
            "N-14/A",
            "N-14/AE",
            "N-14/AE/A",
            "N-14 8C",
            "N-14 8C/A",
            "F-1",
            "F-1/A",
            "F-1MEF",
            "F-2",
            "F-2/A",
            "F-2D",
            "F-2DPOS",
            "F-2MEF",
            "F-3MEF",
            "F-4MEF",
            "F-9MEF",
            "F-10MEF",
            "F-3",
            "F-3/A",
            "F-3D",
            "F-3DPOS",
            "F-4",
            "F-4/A",
            "F-6",
            "F-6/A",
            "F-6 POS",
            "F-6EF",
            "F-6EF/A",
            "20FR12B",
            "20FR12B/A",
            "20FR12G",
            "20FR12G/A",
            "24F-1",
            "24F-2EL",
            "24F-2EL/A",
            "24F-2NT",
            "24F-2NT/A",
            "POS462B",
            "POS462C",
            "8-A12B",
            "8-A12B/A",
            "8-A12G",
            "8-A12G/A",
            "8-B12B",
            "8-B12B/A",
            "8-B12G",
            "8-B12G/A",
            "8A12BEF",
            "8A12BT",
            "8A12BT/A",
            "485A24E",
            "485A24F",
            "485APOS",
            "485B24E",
            "485B24F",
            "485BPOS"
        ]
    },
    "Registration Withdrawal and Termination Statements": {
        "color": "danger",
        "filingArray": [
            "RW",
            "AW",
            "15-12G",
            "15-12G/A",
            "15-15D",
            "15-15D/A",
            "15-12B",
            "15-12B/A",
            "24F-2TM"
        ]
    },
    "Proxies and Information Statements": {
        "color": "primary",
        "filingArray": [
            "PRE 14A",
            "PREC14A",
            "PREC14C",
            "PREN14A",
            "PREM14A",
            "PREM14C",
            "PRES14A",
            "PRES14C",
            "PRE 14C",
            "PRER14A",
            "PRER14C",
            "PRE13E3",
            "PRE13E3/A",
            "PRRN14A",
            "PX14A6G",
            "DEF 14A",
            "DEFM14A",
            "DEFM14C",
            "DEFS14A",
            "DEFS14C",
            "DEFC14A",
            "DEFC14C",
            "DEFA14A",
            "DEFN14A",
            "DFRN14A",
            "DFAN14A",
            "DEF13E3",
            "DEF13E3/A",
            "DEFA14C",
            "DEFR14C",
            "DEFR14A"
        ]
    },
    "Quarterly Reports": {
        "color": "teal",
        "filingArray": [
            "10-Q",
            "10-Q/A",
            "10QSB",
            "10QSB/A",
            "NT 10-Q",
            "NT 10-Q/A",
            "10-QT",
            "10-QT/A",
            "13F-E",
            "13F-E/A",
            "13F-HR",
            "13F-HR/A",
            "13F-NT",
            "13F-NT/A",
            "13F-HR",
            "13F-HR/A"
        ]
    },
    "Annual Reports": {
        "color": "info",
        "filingArray": [
            "ARS",
            "10-K",
            "10-K/A",
            "10-K405",
            "10-K405/A",
            "NT 10-K",
            "NT 10-K/A",
            "10KSB",
            "10KSB/A",
            "10-C",
            "10-C/A",
            "10-KT",
            "10-KT/A",
            "10KSB40",
            "10KSB40/A",
            "10KT405",
            "10KT405/A",
            "11-KT",
            "11-KT/A",
            "18-K",
            "18-K/A",
            "11-K",
            "11-K/A",
            "NT 11-K",
            "NT 11-K/A",
            "NSAR-A",
            "NSAR-A/A",
            "NSAR-AT",
            "NSAR-AT/A",
            "NSAR-B",
            "NSAR-B/A",
            "NSAR-BT",
            "NSAR-BT/A",
            "NSAR-U",
            "NSAR-U/A",
            "NT-NSAR",
            "NT-NSAR/A",
            "N-30D",
            "N-30D/A",
            "20-F",
            "20-F/A",
            "ARS"
        ]
    },
    "Statements of Ownership": {
        "color": "light",
        "filingArray": [
            "SC 13D",
            "SC 13D/A",
            "SC 13G",
            "SC 13G/A",
            "SC 13E1",
            "SC 13E1/A",
            "SC 13E3",
            "SC 13E3/A",
            "SC 13E4",
            "SC 13E4/A",
            "SC 14D1",
            "SC 14D1/A",
            "SC 14D9",
            "SC 14D9/A",
            "SC 14F1",
            "SC 14F1/A",
            "SC TO-C",
            "SC TO-C/A",
            "SC TO-T",
            "SC TO-T/A",
            "SC TO-I",
            "SC TO-I/A"
        ]
    },
    "Insider Trading": {
        "color": "dark",
        "filingArray": [
            "3",
            "3/A",
            "4",
            "4/A",
            "5",
            "5/A",
            "144",
            "144/A"
        ]
    },
    "Filings pursuant to the Trust Identure Act": {
        "color": "danger",
        "filingArray": [
            "305B2",
            "305B2/A",
            "T-3",
            "T-3/A"
        ]
    },
    "Filings pursuant to the Public Utility Holding Company Act": {
        "color": "indigo",
        "filingArray": [
            "U-1",
            "U-1/A",
            "U-13-1",
            "U-13-1/A",
            "U-12-IB",
            "U-12-IB",
            "U-13E-1",
            "U-13E-1/A",
            "U-13-60",
            "U-13-60/A",
            "U-33-S",
            "U-3A-2",
            "U-3A-2/A",
            "U-3A3-1",
            "U-3A3-1/A",
            "U-57",
            "U-57/A",
            "U-6B-2",
            "U-7D",
            "U-7D/A",
            "U-R-1",
            "45B-3",
            "45B-3/A",
            "U5A",
            "U5B",
            "U5B/A",
            "U5S",
            "U-9C-3",
            "U-9C-3/A",
            "U-12-IA",
            "U-12-IA/A",
            "U5S/A",
            "35-APP",
            "35-APP/A",
            "35-CERT",
            "35-CERT/A"
        ]
    },
    "Miscellaneous Filings": {
        "color": "orange",
        "filingArray": [
            "8-K",
            "8-K/A",
            "N-14AE",
            "N-14AE/A",
            "N-30B-2",
            "2-E",
            "2-E/A",
            "SP 15D2",
            "SP 15D2/A",
            "NT 15D2",
            "NT 15D2/A",
            "6-K",
            "6-K/A",
            "8-K12G3",
            "8-K12G3/A",
            "8-K15D5",
            "8-K15D5/A"
        ]
    }
}